<?php
if (isset($_SESSION['lang'])) {
    if ($_SESSION['lang'] == 'ru') {
        require('language/ru/templates/header/menu.phtml');
    }
    if ($_SESSION['lang'] == 'en') {
        require('language/en/templates/header/menu.phtml');
    }
    if ($_SESSION['lang'] == 'ua') {
        require('language/ua/templates/header/menu.phtml');
    }
} else {
    require('language/ru/templates/header/menu.phtml');
}
?>
<div class="menu animated bounceInRight" id="menu">
    <span class="tel" data-title="+38-(097)-851-97-94 +38-(097)-486-53-45">
        <a href="#"><i class="phone fas fa-phone"></i></a>
    </span>
   
    <ul>
        <li><a href="#oncl"><i class="fas fa-home"></i></a></li>
        <li><a href="#about"><?php echo $about; ?></a></li>
        <li><a href="#works"><?php echo $works; ?></a></li>
        <li><a href="#contact"><?php echo $contact; ?></a></li>
    </ul>
</form>
</div>

<script type="text/javascript">
 $(document).ready(function(){
    $("#menu, #swipe-about, #swipe-works, #swipe-contact").on("click","a", function (event) {
        event.preventDefault();
        var id  = $(this).attr('href'),
        top = $(id).offset().top;
        $('body,html').animate({scrollTop: top}, 500);
    });
});
</script>
