<html doctype="html">
<head>
    <title>{{$title}}</title>
    <meta name="title" content="{{$title}}" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta description="услуги вашой фирмы компании" keywords="ключевые слова">
    {{$headfiles}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="shortcut icon" href="/img/icon.png" type="image/x-icon">
    <link rel="stylesheet" href="../styles/animate.css">
    <link rel="stylesheet" href="../styles/proba.scss">
    <link rel="stylesheet" href="../styles/preload-site.css">
    <script type="text/javascript" src="../script/jQuery.js"></script>
</head>
<body class="mCustomScrollbar">
    {{$header}}
    {{$content}}
    {{$footer}}
    <script type="text/javascript" src="../script/scrollwebsite.js"></script>
    <script type="text/javascript" src="../script/script-scroll-block.js"></script>
    <script type="text/javascript">$(window).on('load', function () {
    var $preloader = $('#p_prldr'),
        $svg_anm   = $preloader.find('.svg_anm');
    $svg_anm.fadeOut();
    $preloader.delay(550).fadeOut('slow');
});</script>
</body>
</html>