<?php
if (isset($_SESSION['lang'])) {
	if ($_SESSION['lang'] == 'ru') {
		require_once('language/ru/templates/main.phtml');
	}
	if ($_SESSION['lang'] == 'en') {
		require_once('language/en/templates/main.phtml');
	}
	if ($_SESSION['lang'] == 'ua') {
		require_once('language/ua/templates/main.phtml');
	}
} else {
	require_once('language/ru/templates/main.phtml');
}
?>
<div id="oncl" class="name">
	<section id="ex1">
		<div class="none">
			<div class="content">
				<article class="post">
					<div class="name_con">
						<p class="slogan"><?php echo $slogan; ?></p>
						<h1>MY FREELANCER</h1>
						<p><?php echo $pod_slogan; ?></p>

					</div>	
				</article>
				<div class="swipe-down animated fadeInDown infinite" id="swipe-about">	
					<a href="#about"><i class="fas fa-chevron-down"></i></a>
				</div>
			</div>
		</div>
	</section>
</div>
<div class="about" id="about">
	<section id="ex2">
		<div class="content">	

			<div class="about-us">
				<h1><img src="img/user.png" alt="<?php echo $about; ?>"></h1>
				<h1><?php echo $about; ?></h1>
				<article class="post">
					<div class="circle-block">
						<div class="circle"><i class="pa-g fas fa-thumbs-up"></i></div>

						<p class="animated pulse infinite"><?php echo $qualitatively; ?></p>
					</div>
				</article>	
				<div class="circle-block">
					<div class="circle"><i class="pa-g far fa-clock"></i></div>

					<p class="animated pulse infinite"><?php echo $fast; ?></p>
				</div>	
				<article class="post last">
					<div class="circle-block">
						<div class="circle"><i class="pa-g fas fa-money-bill-alt"></i></div>

						<p class="animated pulse infinite"><?php echo $cheap; ?></p>
					</div>
				</article>
				<div class="about-bottom">
					<p ><?php echo $about_bottom; ?></p>
					<div class="swipe-down" id="swipe-works">	
						<a href="#works"><i class="fas fa-chevron-down"></i></a>
					</div>
				</div>
			</article>
		</div>

	</div>
</section>
</div>
<div class="works" id="works">
	<div class="content">
		<div class="works-con">
			<h1><?php echo $our_works;?></h1>
			<p class="opis-works"><?php echo $description_work;?></p>
			<div class="up-works-block">
				<ul>
					
					<li><div class="page">
						<div class="page__demo">
							<div class="page__container">
								<div class="photobox photobox_type1">
									<div class="photobox__previewbox">
										<a href="http://methodist.pp.ua/" target="_blank">    <div class="photobox photobox_type9">
											<div class="photobox__previewbox">
												<img src="img/2.png" class="photobox__preview" alt="<?php echo $name_site1;?>">
												<span class="photobox__label"><h2><?php echo $name_site1;?></h2> <br/> <p><?php echo $site1;?></p></span>
											</div>
										</div>   </a>  


									</div>
								</div>      
							</div>  
						</div>
					</div></li>

					<li> <div class="page">
						<div class="page__demo">
							<div class="page__container">
								<div class="photobox photobox_type1">
									<div class="photobox__previewbox">
										<a href="http://agrobaza.net.ua/" target="_blank">    <div class="photobox photobox_type9">
											<div class="photobox__previewbox">
												<img src="img/4.png" class="photobox__preview" alt="<?php echo $name_site2;?>">
												<span class="photobox__label"><h2><?php echo $name_site2;?></h2> <br/> <p><?php echo $site2;?></p>	</span>
											</div>
										</div>   </a>  


									</div>
								</div>      
							</div>  
						</div>
					</div></li>

					<li><div class="page">
						<div class="page__demo">
							<div class="page__container">
								<div class="photobox photobox_type1">
									<div class="photobox__previewbox">
										<a href="	" target="_blank">    <div class="photobox photobox_type9">
											<div class="photobox__previewbox">
												<img src="img/3.png" class="photobox__preview" alt="<?php echo $name_site3;?>">
												<span class="photobox__label"><h2><?php echo $name_site3;?></h2> <br/> <p><?php echo $site3;?></p>	</span>
											</div>
										</div>   </a>  


									</div>
								</div>      
							</div>  
						</div>
					</div></li>
					<div class="swipe-down" id="swipe-about">	
						<a href="#argument"><i class="fas fa-chevron-down"></i></a>
					</div>
				</ul>
			</div>
		</div>
	</div>
	<div class="argument" id="argument">
	
			<div class="content">
					<section id="ex3">
				<h1 class="post"><?php echo $argument;?></h1>
				<br/><br/>
				<div class="post last"><p ><?php echo $argument_description1;?></p> <br/><br/>
					<p class="p2"><?php echo $argument_description2;?></p>
					<br/><br/>
					<p class="p3"><?php echo $argument_description3;?></p>
				</div>
				<br><br><br><br><br><br>
				<div class="swipe-down" id="swipe-contact">	
					<a href="#contact"><i class="fas fa-chevron-down"></i></a>
				</div>
					</section>
			</div>
	
	</div>
	<div class="contact" id="contact"> 
		
		<div class="content">
			<section id="ex4">
			<div class="contact-form">
				<div class="contact-left">
					<h1><?php echo $conctakt_form;?></h1>
					<p><?php echo $conctakt_description;?></p>
					<form action="/index" enctype="multipart/form-data" method="post">
						<input type="text" name="name" placeholder="<?php echo $conctakt_name;?>">
						<input type="email" name="email" placeholder="<?php echo $conctakt_email;?>"> <br/><br/>
						<textarea name="coment" id="" cols="30" rows="10" placeholder="<?php echo $conctakt_comment;?>"></textarea>
						<br/><br/>
						<input type="submit" name="send" value="<?php echo $conctakt_send;?>">
					</form>

				</div>
				<div class="contact-right">
					<div class="con-right">
						<h1><?php echo $our_address;?></h1>
						<p><?php echo $city1;?><br/> <?php echo $phone;?>: +38-(097)-851-97-94</p>
						<br/>
						<p><?php echo $city2;?><br/> <?php echo $phone;?>: +38-(097)-486-53-45</p>
						<h1><?php echo $conect;?></h1>
						<div class="con-left">
							<a href="skype:witalik_win;live:684c013e26be73c5;?chat">
								<i class="fab fa-skype"></i>Skype
							</a>
							<br/><br/>

							<ul class="save-right"><i class="fab fa-telegram-plane"></i>    Telegram
								<li class="save-right">
									<ul class="subsave">
										<li><a href="tg://resolve?domain=Yaroslav Bulavin"><?php echo $city1;?></a></li>
										<li><a href="tg://resolve?domain=Віталік Булавін"><?php echo $city2;?></a></li>
									</ul>
								</li>

							</ul>
							<br/>
							<ul class="save-right"><i class="fab fa-viber"></i>         Viber		
								<li class="hover-save">
									<ul class="subsave">
										<li><a href="viber://chat?number=+380978519794"><?php echo $city1;?></a></li>
										<li><a href="viber://chat?number=+380974865345"><?php echo $city2;?></a></li>
									</ul>
								</li>
							</ul>			
						</div>
								</section>
					</div>
				</div>	
			</div>

		</div>

</div>