<div id="oncl" class="name">
	<section id="ex1">
	<div class="none">
		<div class="content">
			<article class="post">
			<div class="name_con">
				<p class="slogan">МОЛОДАЯ КОМАНДА</p>
				<h1>MY FREELANCER</h1>
				<p>Быстро выполнит ваши потребности!</p>

			</div>	
			</article>
		</div>
	</div>
	</section>
</div>
<div class="about" id="about">
	<section id="ex2">
	<div class="content">	
		
		<div class="about-us">
			<h1><img src="img/user.png" alt=""></h1>
			<h1>Про нас</h1>
			<article class="post">
			<div class="circle-block">
				<div class="circle"><i class="pa-g fas fa-thumbs-up"></i></div>

				<p class="animated pulse infinite">КАЧЕСТВЕННО</p>
			</div>
			</article>	
			<div class="circle-block">
				<div class="circle"><i class="pa-g far fa-clock"></i></div>

				<p class="animated pulse infinite">БЫСТРО</p>
			</div>	
			<article class="post last">
			<div class="circle-block">
				<div class="circle"><i class="pa-g fas fa-money-bill-alt"></i></div>

				<p class="animated pulse infinite">ДЕШЕВО</p>
			</div>
			</article>
				<div class="about-bottom">
				<p >Mы перспективная молодая команда, которая сделает Вам сайт наиболее удобным и современным, за короткое время и минимальную сумму.</p>
			</div>
			</article>

			
		</div>

	</div>
	</section>
</div>
<div class="works" id="works">
	<section id="ex3">
	<div class="content">
		<div class="works-con">
			<h1>Наши работы</h1>
			<p class="opis-works">Здесь вы можете увидеть перечень наших работ.</p>
			<div class="up-works-block">
				<ul>
				
					<li> <div class="image"><img src="img/4.png" alt="Alt">	</div><a href="http://agrobaza.net.ua/" target="_blank"><span class="descr"><h2>АгроБаза</h2> <br/><p>Интернет-магазин</p></span></a></li>
			
					<li> <div class="image">	</div><a href="http://methodist.pp.ua/" target="_blank"><span class="descr"><h2>Мій Методист</h2> <br/><p>Информационный сайт</p></span></a><img src="img/2.png" alt="Alt"></li>
	
					
					<li> <div class="image">	</div><a href="#" target="_blank"><span class="descr"><h2>AGROBAZA</h2> <br/><p>Интернет-магазин</p></span></a><img src="img/3.png" alt="Alt"></li>
						
				</ul>
			</div>
		</div>
	</div>
</section>
</div>
<div class="sayings">
	<div class="content">

	</div>
</div>
<div class="contact" id="contact"> 
	<div class="content">
		<div class="contact-form">
			<div class="contact-left">
				<h1>Контактная форма</h1>
				<p>Здесь вы можете задать интересующий вас вопрос, или же связаться с нами для заказа работы.</p>
				<form action="/index" method="post">
					<input type="text" name="name" placeholder=" ваше имя">
					<input type="email" name="email" placeholder=" ваш email"> <br/><br/>
					<textarea name="coment" id="" cols="30" rows="10" placeholder=" ваш коментарий"></textarea>
					<br/><br/>
					<input type="submit" name="send" value="Отправить">
				</form>

			</div>
			<div class="contact-right">
				<div class="con-right">
					<h1>Наш адрес</h1>
					<p>г. Киев <br/> тел: +38-(097)-851-97-94</p>
					<br/>
					<p>г. Ровно <br/> тел: +38-(097)-486-53-45</p>
					<h1>Связаться с нами</h1>
					<div class="con-left">
						<a href="skype:witalik_win;live:684c013e26be73c5;?chat">
							<i class="fab fa-skype"></i>Skype
						</a>
						<br/><br/>

						<ul class="save-right"><i class="fab fa-telegram-plane"></i>    Telegram
							<li class="save-right">
								<ul class="subsave">
									<li><a href="tg://resolve?domain=Yaroslav Bulavin">Киев</a></li>
									<li><a href="tg://resolve?domain=Віталік Булавін">Ровно</a></li>
								</ul>
							</li>

						</ul>
						<br/>
						<ul class="save-right"><i class="fab fa-viber"></i>         Viber		
							<li class="hover-save">
								<ul class="subsave">
									<li><a href="viber://chat?number=+380978519794">Киев</a></li>
									<li><a href="viber://chat?number=+380974865345">Ровно</a></li>
								</ul>
							</li>
						</ul>
						
						

					</div>

				</div>
			</div>	
		</div>
	</div>
</div>